default: &default
  adapter: postgresql
  user: postgres
  password: test
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: atache

test:
  <<: *default
  database: atache_test

production:
  <<: *default
  database: atache
